name: tests
  # run lint flake8 and run tests project
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install dependecies
        run: |
          pip install poetry
          make install
      - name: run linter
        run: |
          make lint
      - name: run tests
        run: |
          make test
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0

